---
- name: restart flannel
  service: name=flanneld state=restarted

- name: restart docker
  service: name=docker state=stopped
  notify:
          - delete docker0
          - start docker

- name: delete docker0
  command: ip link delete docker0
  ignore_errors: yes

- name: start docker
  service: name=docker state=started

- name: restart kubelet
  service: name=kubelet state=restarted
