---
- name: restart daemons
  local_action: command /bin/true
  notify:
          - restart kubelet
          - restart proxy

- name: restart kubelet
  service: name=kubelet state=restarted

- name: restart proxy
  service: name=kube-proxy state=restarted
