---
- name: Install etcd
  yum: pkg=etcd state=latest disable_gpg_check=yes

- name: Write etcd global config file
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  notify:
        - restart etcd

- name: Enable etcd
  service: name=etcd enabled=yes state=started

- include: firewalld.yml
  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0
