---
- name: restart daemons
  local_action: command /bin/true
  notify:
          - restart apiserver
          - restart controller-manager

- name: restart apiserver
  service: name=kube-apiserver state=restarted

- name: restart controller-manager
  service: name=kube-controller-manager state=restarted
