---
- hosts: masters
  tasks:
  #- name: Install etcd
  #yum: pkg=etcd state=latest
  - name: write the config files for api server
    template: src=templates/apiserver.j2 dest=/etc/kubernetes/apiserver
  - name: write the config files for controller-manager
    template: src=templates/controller-manager.j2 dest=/etc/kubernetes/controller-manager
  - name: Enable etcd
    service: name=etcd enabled=yes state=started
  - name: Enable apiserver
    service: name=kube-apiserver enabled=yes state=started
  - name: Enable controller-manager
    service: name=kube-controller-manager enabled=yes state=started
  - name: Firewalld for etcd
    firewalld: port=4001/tcp permanent=true state=enabled
  - name: Firewalld for apiserver
    firewalld: port=8080/tcp permanent=true state=enabled
  handlers:
    - name: restart apiserver
      service: name=kube-apiserver state=restarted
    - name: restart controller-manager
      service: name=kube-controller-manager state=restarted
