---
- name: write the config files for api server
  template: src=apiserver.j2 dest=/etc/kubernetes/apiserver
  notify:
          - restart apiserver

- name: write the config files for controller-manager
  template: src=controller-manager.j2 dest=/etc/kubernetes/controller-manager
  notify:
          - restart controller-manager

- name: Enable apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: Enable controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: Open firewalld port for apiserver
  firewalld: port=8080/tcp permanent=false state=enabled
  when: is_atomic|failed

- name: Save firewalld port for apiserver
  firewalld: port=8080/tcp permanent=true state=enabled
  when: is_atomic|failed

- name: Open ports with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT
  when: is_atomic|success


- name: Save iptables rules
  command: iptables-save
  when: is_atomic|success

