---
- name: write the config files for kubelet
  template: src=kubelet.j2 dest=/etc/kubernetes/kubelet
  notify:
          - restart kubelet

- name: write the config files for proxy
  template: src=proxy.j2 dest=/etc/kubernetes/proxy
  notify:
          - restart proxy

- name: Enable docker
  service: name=docker enabled=yes state=started

- name: Enable kubelet
  service: name=kubelet enabled=yes state=started

- name: Enable proxy
  service: name=kube-proxy enabled=yes state=started

- name: Open firewalld port for the kubelet
  firewalld: port=10250/tcp permanent=false state=enabled
  when: is_atomic|failed

- name: Save firewalld port for the kubelet
  firewalld: port=10250/tcp permanent=true state=enabled
  when: is_atomic|failed

- name: Open ports with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 10250 -j ACCEPT
  when: is_atomic|success


- name: Save iptables rules
  command: iptables-save
  when: is_atomic|success

